baseURL = "https://cove.github.io/"
languageCode = "en-us"
#title = "simpledoc"
theme = "simpledoc"
publishDir = "../"

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]
# Top menu
#[[menu.top]]
#    name = "hugo-simpledoc-theme GitHub Repository"
#    weight = 20
#    url = "https://github.com/aerohub/hugo-simpledoc-theme"
#[[menu.top]]
#    name = "Hugo - A Fast and Flexible Website Generator"
#    weight = 10
#    url = "http://gohugo.io/"
#[[menu.top]]
#    name = "Original WPThemeDoc by Rich Tabor"
#    weight = 30
#    url = "https://github.com/richtabor/WPThemeDoc"

[params]
# description = "Simple"
author = "Cove Schneider"
keywords = ""
headerTitle = "Contents"
headerDescription = ""
bttButton = ""
